export * from './fascicoli-data-filter.pipe';
export * from './registri-data-filter.pipe';
export * from './registri-data-mark.pipe';
export * from './fascicoli-by-titolario-data-filter.pipe'
export * from './mittenti-data-filter.pipe'
export * from './mittenti-data-mark.pipe'
export * from './uffici-data-filter.pipe'
export * from './uffici-data-mark.pipe'
export * from './amministrazioni-data-filter.pipe'
export * from './amministrazioni-data-mark.pipe'
export * from './tags-data-filter.pipe'
export * from './tags-data-mark.pipe'
export * from './file-size.pipe'
export * from './data-mark.pipe';