export const GroupsMockData: any = {
    "response": 200,
    "total_results": 7,
    "limit": "9999",
    "offset": 0,
    "data": [{
        "id": 1,
        "name": "Base",
        "roles": ["ROLE_READ_REGISTRI", "ROLE_READ_FASCICOLI", "ROLE_READ_TITOLARI", "ROLE_READ_AMMINISTRAZIONI", "ROLE_READ_MITTENTI", "ROLE_READ_UTENTI", "ROLE_READ_RUOLICIPE", "ROLE_READ_TAGS", "ROLE_READ_UFFICI"],
        "codice": "0"
    }, {
        "id": 2,
        "name": "Utente parzialmente abilitato",
        "roles": ["ROLE_READ_REGISTRI", "ROLE_READ_FASCICOLI", "ROLE_READ_TITOLARI", "ROLE_READ_AMMINISTRAZIONI", "ROLE_READ_MITTENTI", "ROLE_READ_UTENTI", "ROLE_READ_RUOLICIPE", "ROLE_READ_TAGS", "ROLE_READ_UFFICI"],
        "codice": "1"
    }, {
        "id": 3,
        "name": "Utente mediamente abilitato",
        "roles": ["ROLE_READ_REGISTRI", "ROLE_READ_FASCICOLI", "ROLE_READ_TITOLARI", "ROLE_READ_AMMINISTRAZIONI", "ROLE_READ_MITTENTI", "ROLE_READ_UTENTI", "ROLE_READ_RUOLICIPE", "ROLE_READ_TAGS", "ROLE_READ_UFFICI"],
        "codice": "2"
    }, {
        "id": 4,
        "name": "Utente interamente abilitato",
        "roles": ["ROLE_READ_REGISTRI", "ROLE_READ_FASCICOLI", "ROLE_READ_TITOLARI", "ROLE_READ_AMMINISTRAZIONI", "ROLE_READ_MITTENTI", "ROLE_READ_UTENTI", "ROLE_READ_RUOLICIPE", "ROLE_READ_TAGS", "ROLE_READ_UFFICI"],
        "codice": "3"
    }, {
        "id": 5,
        "name": "Responsabile dei contenuti",
        "roles": ["ROLE_READ_REGISTRI", "ROLE_READ_FASCICOLI", "ROLE_READ_TITOLARI", "ROLE_READ_AMMINISTRAZIONI", "ROLE_READ_MITTENTI", "ROLE_READ_UTENTI", "ROLE_READ_RUOLICIPE", "ROLE_READ_TAGS", "ROLE_READ_UFFICI", "ROLE_CREATE_REGISTRI", "ROLE_CREATE_FASCICOLI", "ROLE_EDIT_FASCICOLI", "ROLE_CREATE_AMMINISTRAZIONI", "ROLE_EDIT_AMMINISTRAZIONI", "ROLE_CREATE_MITTENTI", "ROLE_EDIT_MITTENTI", "ROLE_EDIT_REGISTRI"],
        "codice": "4"
    }, {
        "id": 6,
        "name": "Amministratore del sistema",
        "roles": ["ROLE_CREATE_REGISTRI", "ROLE_DELETE_REGISTRI", "ROLE_EDIT_REGISTRI", "ROLE_READ_REGISTRI", "ROLE_CREATE_FASCICOLI", "ROLE_DELETE_FASCICOLI", "ROLE_EDIT_FASCICOLI", "ROLE_READ_FASCICOLI", "ROLE_CREATE_TITOLARI", "ROLE_DELETE_TITOLARI", "ROLE_EDIT_TITOLARI", "ROLE_READ_TITOLARI", "ROLE_CREATE_AMMINISTRAZIONI", "ROLE_DELETE_AMMINISTRAZIONI", "ROLE_EDIT_AMMINISTRAZIONI", "ROLE_READ_AMMINISTRAZIONI", "ROLE_CREATE_MITTENTI", "ROLE_EDIT_MITTENTI", "ROLE_READ_MITTENTI", "ROLE_CREATE_UTENTI", "ROLE_DELETE_UTENTI", "ROLE_EDIT_UTENTI", "ROLE_READ_UTENTI", "ROLE_CREATE_RUOLICIPE", "ROLE_DELETE_RUOLICIPE", "ROLE_EDIT_RUOLICIPE", "ROLE_READ_RUOLICIPE", "ROLE_CREATE_TAGS", "ROLE_DELETE_TAGS", "ROLE_EDIT_TAGS", "ROLE_READ_TAGS", "ROLE_CREATE_UFFICI", "ROLE_DELETE_UFFICI", "ROLE_EDIT_UFFICI", "ROLE_READ_UFFICI", "ROLE_DELETE_MITTENTI"],
        "codice": "5"
    }, {
        "id": 11,
        "name": "test nuovo gruppo",
        "roles": ["ROLE_READ_REGISTRI", "ROLE_CREATE_FASCICOLI", "ROLE_EDIT_TITOLARI", "ROLE_DELETE_AMMINISTRAZIONI"],
        "codice": "9999"
    }]
}