export const TitolariMockData: any[] = [
    {"id": 0,"codice": 0,"denominazione": 'Documenti di seduta',"descrizione": 'Telex, Appunto generale, passi, etc.'},
    {"id": 1,"codice": 1,"denominazione": 'Segreteria Cipe',"descrizione": 'Competenze CIPE, Regolamento interno CIPE, Regolamento interno Commissioni, Altri organismi in seno al CIPE, ISTAT'},
    {"id": 2,"codice": 2,"denominazione": 'Programmazione Finanziaria',"descrizione": 'Cofinanziamento programmi UE, Aree depresse, Fondo art.19 D.L.vo 96/93'},
    {"id": 3,"codice": 3,"denominazione": 'Ambiente',"descrizione": 'Difesa acqua, difesa aria, difesa suolo, piano biodiversità'},
    {"id": 4,"codice": 4,"denominazione": 'Energia',"descrizione": 'Elettrica, Fonti alternative, Metanizzazione, Nucleare, Risparmio energetica'},
    {"id": 5,"codice": 5,"denominazione": 'Montagna',"descrizione": 'Montagna'},
    {"id": 6,"codice": 6,"denominazione": 'Agricoltura',"descrizione": 'Agro-forestale, Agro-industriale, Pesca e acquacoltura, Zootecnia'},
    {"id": 7,"codice": 7,"denominazione": 'Industria Commercio ed Artigianato',"descrizione": 'Attività estrattiva, Commercio e artigianato, Manifatturiere, Cooperazione int.le, Commercio estero'},
    {"id": 8,"codice": 8,"denominazione": 'Programmazione negoziata',"descrizione": 'Accordi di programma, Contratti d\'area, Contratti di programma, Intese di programma, Patti territoriali'},
    {"id": 9,"codice": 9,"denominazione": 'Occupazione e lavoro',"descrizione": 'Formazione professionale, Occupazione, Previdenza e assistenza, Tutela salariale'},
    {"id": 10,"codice": 10,"denominazione": 'Ricerca e istruzione',"descrizione": 'Istruzione, Ricerca'},
    {"id": 11,"codice": 11,"denominazione": 'Infrastrutture e trasporti',"descrizione": 'Aeroporti, Edilizia pubblica, Ferrovie, Interporti, Opere idriche, Porti, Strade e autostrade, Trasporto rapido di massa'},
    {"id": 12,"codice": 12,"denominazione": 'Sanita',"descrizione": 'Edilizia sanitaria, Fondo Sanitario Nazionale (parte corrente e capitale)'},
    {"id": 13,"codice": 13,"denominazione": 'Servizi',"descrizione": 'Assicurazioni, Credito, Turismo'},
    {"id": 14,"codice": 14,"denominazione": 'Tariffe',"descrizione": 'Acqua e depurazione, Autostradali, Ferroviarie, Telefoniche e postali'},
    {"id": 15,"codice": 15,"denominazione": 'Farmaci',"descrizione": 'Prezzi, Contenzioso'},
    {"id": 16,"codice": 16,"denominazione": 'Terremoto',"descrizione": 'Terremoto'},
    {"id": 17,"codice": 17,"denominazione": 'Gestione contabile',"descrizione": 'Spese in conto capitale, Spese di esercizio, Convenzioni ex Agensud'},
    {"id": 18,"codice": 18,"denominazione": 'Organizzazione',"descrizione": 'Pianificazione e controllo, Gestione del personale, Procedure e informatizzazione'},
    {"id": 19,"codice": 19,"denominazione": 'Attività diverse',"descrizione": 'Telecomunicazioni, FIO, Varie'}
];